name: atomic-red-team-buildx

on:
  schedule:
        - cron: "15 6 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/atomic-red-team
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/atomic-red-team
          file: ./dockerfiles/atomic-red-team/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/atomic-red-team:latest
      - 
        name: Get atomic-red-team version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/atomic-red-team:latest
          options: -v $(realpath ${GITHUB_ENV}):/tmp/github.env
          shell: bash
          run: echo version=$(pwsh -c "get-module -listavailable -name invoke-atomicredteam | format-table -property version -hidetableheaders | xargs") >> /tmp/github.env
      -
        name: Build and push heywoodlh/atomic-red-team
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/atomic-red-team
          file: ./dockerfiles/atomic-red-team/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/atomic-red-team:latest,heywoodlh/atomic-red-team:${{ env.version }}
