name: beef-buildx

on:
  schedule:
    - cron: "30 0 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/beefproject/beef
        uses: actions/checkout@master
        with:
          name: beefproject/beef
          repository: beefproject/beef
          path: ./beef
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/beef
        uses: docker/build-push-action@v2
        with:
          context: ./beef
          file: ./beef/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/beef:latest
      - 
        name: Get beef version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/beef:latest
          run: echo "::set-output name=version::$(cat /beef/VERSION | tail -1)"
      -
        name: Build and push heywoodlh/beef:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./beef
          file: ./beef/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/beef:latest,heywoodlh/beef:${{ steps.version.outputs.version }}
