name: clamscan-buildx

on:
  schedule:
        - cron: "15 3 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/clamscan locally 
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/clamscan
          file: ./dockerfiles/clamscan/Dockerfile
          load: true
          tags: heywoodlh/clamscan:latest
      - 
        name: Get clamscan version
        id: version
        run: echo "::set-output name=version::$(docker run -i --rm heywoodlh/clamscan apk --no-cache list | grep clamav-scanner | awk '{print $1}' | cut -d'-' -f3')"
      -
        name: Build and push heywoodlh/clamscan
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/clamscan
          file: ./dockerfiles/clamscan/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/clamscan:latest,heywoodlh/clamscan:${{ steps.version.outputs.version }}
