name: cloudtube-buildx

on:
  schedule:
        - cron: "15 11 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current month
        run: echo date=$(date +%Y_%m) >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/cloudtube
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/cloudtube
          file: ./dockerfiles/cloudtube/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/cloudtube:latest,heywoodlh/cloudtube:${{ env.date }}
