name: crackmapexec-buildx

on:
  schedule:
        - cron: "30 4 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles 
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/crackmapexec
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/crackmapexec
          file: ./dockerfiles/crackmapexec/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/crackmapexec:latest
      - 
        name: Get crackmapexec version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/crackmapexec:latest
          run: echo "::set-output name=version::$(dpkg -l | grep crackmapexec | awk '{print $3}')"
      -
        name: Build and push heywoodlh/crackmapexec
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/crackmapexec
          file: ./dockerfiles/crackmapexec/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/crackmapexec:latest,heywoodlh/crackmapexec:${{ steps.version.outputs.version }}
