name: cups-buildx

on:
  schedule:
    - cron: "30 0 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: lemariva/wifi-cups-server
          repository: lemariva/wifi-cups-server
          path: ./wifi-cups-server
      - name: modify Dockerfile
        run: |
          sed -i 's/FROM balenalib\/raspberry-pi-debian:buster/FROM debian:buster/' wifi-cups-server/cup-docker/Dockerfile
          sed -i '/^RUN \[ "cross-build-start" \]/,/.*description="Raspbian.*/d' wifi-cups-server/cup-docker/Dockerfile
          sed -i '/RUN \[ "cross-build-end/d' wifi-cups-server/cup-docker/Dockerfile
          echo 'LABEL maintainer=heywoodlh' >> wifi-cups-server/cup-docker/Dockerfile
          echo '#Original Dockerfile at https://github.com/lemariva/wifi-cups-server -- thank you lemariva!' >> wifi-cups-server/cup-docker/Dockerfile
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/cups
        uses: docker/build-push-action@v2
        with:
          context: ./wifi-cups-server/cup-docker
          file: ./wifi-cups-server/cup-docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/cups:latest
      - 
        name: Get cups version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/cups:latest
          run: echo "::set-output name=version::$(dpkg -l | grep 'cups-daemon' | awk '{print $3}' | cut -d'-' -f1')"
      -
        name: Build and push heywoodlh/cups
        uses: docker/build-push-action@v2
        with:
          context: ./wifi-cups-server/cup-docker
          file: ./wifi-cups-server/cup-docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/cups:latest,heywoodlh/cups:${{ steps.date.outputs.version }}

