name: dnscat2-buildx

on:
  schedule:
        - cron: "0 0 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dnscat2
        uses: actions/checkout@master
        with:
          name: heywoodlh/dnscat2
          repository: heywoodlh/dnscat2
          path: ./dnscat2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/dnscat2 locally
        uses: docker/build-push-action@v2
        with:
          context: ./dnscat2/server
          file: ./dnscat2/server/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/dnscat2:latest
      -
        name: Get dnscat2 version
        run: |
          echo version=$(docker run -i --rm heywoodlh/dnscat2 --version | tail -1 | awk '{print $2}') >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/dnscat2
        uses: docker/build-push-action@v2
        with:
          context: ./dnscat2/server
          file: ./dnscat2/server/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/dnscat2:latest,heywoodlh/dnscat2:${{ env.version }}
