name: drawio-buildx

on:
  schedule:
    - cron: "30 0 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/jgraph/docker-drawio
        uses: actions/checkout@master
        with:
          name: jgraph/docker-drawio
          repository: jgraph/docker-drawio
          path: ./docker-drawio
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m_snapshot)"
      -
        name: Build and push heywoodlh/drawio
        uses: docker/build-push-action@v2
        with:
          context: ./docker-drawio/debian/
          file: ./docker-drawio/debian/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/drawio:latest,heywoodlh/drawio:${{ steps.date.outputs.date }}
