name: fauxpilot-buildx

on:
  schedule:
        - cron: "0 12 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/fauxpilot/fauxpilot
        uses: actions/checkout@master
        with:
          name: fauxpilot/fauxpilot
          repository: fauxpilot/fauxpilot
          path: ./fauxpilot
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/fauxpilot
        uses: docker/build-push-action@v2
        with:
          context: ./fauxpilot
          file: ./fauxpilot/triton.Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/fauxpilot:latest
