name: filesystem-livesync-buildx

on:
#  schedule:
#        - cron: "0 4 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/vrtmrz/filesystem-livesync
        uses: actions/checkout@master
        with:
          name: vrtmrz/filesystem-livesync
          repository: vrtmrz/filesystem-livesync
          path: ./filesystem-livesync
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m)"
      -
        name: Build and push heywoodlh/filesystem-livesync
        uses: docker/build-push-action@v2
        with:
          context: ./filesystem-livesync
          file: ./filesystem-livesync/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/filesystem-livesync:latest,heywoodlh/filesystem-livesync:${{ steps.date.outputs.date }}
