name: flan-scan-buildx

on:
  schedule:
    - cron: "45 0 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/cloudflare/flan
        uses: actions/checkout@master
        with:
          name: cloudflare/flan
          repository: cloudflare/flan
          path: ./flan
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m_snapshot)"
      -
        name: Build and push heywoodlh/flan-scan
        uses: docker/build-push-action@v2
        with:
          context: ./flan
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/flan-scan:latest,heywoodlh/flan-scan:${{ steps.date.outputs.date }}
