name: focalboard-buildx

on:
  schedule:
        - cron: "0 4 * * Sun"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/mattermost-community/focalboard
        uses: actions/checkout@master
        with:
          name: mattermost-community/focalboard
          repository: mattermost-community/focalboard
          path: ./focalboard-upstream
      -
        name: rebase fixed-branch against upstream
        run: |
          git clone https://github.com/DanArmor/focalboard # contains fix for Dockerfile
          git -C ./focalboard remote add upstream https://github.com/mattermost-community/focalboard
          git -C ./focalboard fetch upstream
          git config --global user.email "github-actions@localhost"
          git config --global user.name "GitHub Actions"
          git -C ./focalboard rebase upstream/main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get focalboard sha
        run: |
          echo sha=$(git -C ./focalboard-upstream rev-parse --short HEAD) >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/focalboard:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v3
        with:
          context: ./focalboard
          file: ./focalboard/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/focalboard:latest,heywoodlh/focalboard:${{ env.sha }}
