name: github-actions-runner-buildx

on:
  schedule:
    - cron: "30 6 * * Sun"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download github-actions-runner repository
        run: |
          git clone https://github.com/heywoodlh/dockerfiles --depth=1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/github-actions-runner locally
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/github-actions-runner
          file: ./dockerfiles/github-actions-runner/Dockerfile
          load: true
          tags: heywoodlh/github-actions-runner-local:latest
      -
        name: Get github-actions-runner version
        id: version
        run: echo version=$(docker run -i --entrypoint="bash" --rm heywoodlh/github-actions-runner-local:latest -c "cat /version") >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/github-actions-runner:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/github-actions-runner
          file: ./dockerfiles/github-actions-runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/github-actions-runner:latest,heywoodlh/github-actions-runner:${{ env.version }}
