name: gitleaks-buildx

on:
  schedule:
    - cron: "30 1 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/zricethezav/gitleaks
        uses: actions/checkout@master
        with:
          name: zricethezav/gitleaks 
          repository: zricethezav/gitleaks 
          path: /go/src/github.com/zricethezav/gitleaks
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/gitleaks
        uses: docker/build-push-action@v2
        with:
          context: ./gitleaks
          file: ./gitleaks/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/gitleaks:latest
      -
        name: Get gitleaks version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/gitleaks:latest
          run: echo "::set-output name=version::$(gitleaks version)"
      -
        name: Build and push heywoodlh/gitleaks:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./gitleaks
          file: ./gitleaks/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/gitleaks:latest,heywoodlh/gitleaks:${{ steps.version.outputs.version }}
