name: grayjay-buildx

on:
  schedule:
        - cron: "30 6 * * Tue"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone grayjay-desktop-container
        uses: actions/checkout@master
        with:
          # TODO: use upstream when merged
          name: heywoodlh/grayjay-desktop-container
          repository: heywoodlh/grayjay-desktop-container
          ref:
          path: ./grayjay
          submodules: recursive
      -
        name: Pull lfs files
        run: |
          git -C ./grayjay lfs pull --include="vendor/Grayjay.Desktop/JustCef/prebuilt/linux-x64/**,vendor/Grayjay.Desktop/Grayjay.ClientServer/deps/linux-x64/**"
          cd ./grayjay && ./scripts/patch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get current month
        run: echo date=$(date +%Y_%m) >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/grayjay
        uses: docker/build-push-action@v2
        with:
          context: ./grayjay
          file: ./grayjay/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/grayjay:latest,heywoodlh/grayjay:${{ env.date }}
