name: gscript-buildx

on:
  schedule:
        - cron: "0 0 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/gscript
        uses: actions/checkout@master
        with:
          name: heywoodlh/gscript
          repository: heywoodlh/gscript
          path: ./gscript
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/gscript
        uses: docker/build-push-action@v2
        with:
          context: ./gscript/build
          file: ./gscript/build/Dockerfile-minimal
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/gscript:latest
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m)"
      - 
        name: Get gscript version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/gscript:latest
          run: echo "::set-output name=version::$(gscript --version)"
      -
        name: Build and push heywoodlh/gscript
        uses: docker/build-push-action@v2
        with:
          context: ./gscript/build/
          file: ./gscript/build/Dockerfile-minimal
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/gscript:latest,heywoodlh/gscript:${{ steps.version.outputs.version  }}
