name: guerrillamail-buildx

on:
  schedule:
        - cron: "0 12 1 * *"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/guerrillamail
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/guerrillamail
          file: ./dockerfiles/guerrillamail/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/guerrillamail:latest
      - 
        name: Get guerrillamail version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/guerrillamail:latest
          run: echo "::set-output name=version::$(pip freeze | grep 'python-guerrillamail' | cut -d= -f3)"
      -
        name: Build and push heywoodlh/guerrillamail
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/guerrillamail
          file: ./dockerfiles/guerrillamail/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/guerrillamail:latest,heywoodlh/guerrillamail:${{ steps.version.outputs.version  }}
