name: heralding-buildx

on:
  schedule:
    - cron: "55 0 * * Sun"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download heralding repository
        run: |
          git clone https://github.com/johnnykv/heralding
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/heralding
        uses: docker/build-push-action@v2
        with:
          context: ./heralding
          file: ./heralding/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/heralding:latest
      -
        name: Get heralding version
        id: version
        run: echo version=$(cat heralding/heralding/__init__.py | awk '{print $3}' | tr -d '"') >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/heralding:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./heralding
          file: ./heralding/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/heralding:${{ env.version }},heywoodlh/heralding:latest
