name: hershell-buildx

on:
  schedule:
        - cron: "45 4 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/lesnuages/hershell
        uses: actions/checkout@master
        with:
          name: lesnuages/hershell 
          repository: lesnuages/hershell
          path: ./hershell
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/hershell
        uses: docker/build-push-action@v2
        with:
          context: ./hershell
          file: ./hershell/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/hershell:latest
