name: http-files-buildx

on:
  schedule:
    - cron: "0 2 * * Mon"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/http-files locally
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/http-files
          file: ./dockerfiles/http-files/Dockerfile
          load: true
          tags: heywoodlh/http-files:latest
      -
        name: Get version
        run: |
          echo version=$(docker run -i --rm --entrypoint=caddy heywoodlh/http-files:latest --version | awk '{print $1}' | xargs) >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/http-files:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/http-files
          file: ./dockerfiles/http-files/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/http-files:latest,heywoodlh/http-files:${{ env.version }}
