name: inim-web-buildx

on:
  schedule:
        - cron: "0 5 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/inim-web
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/inim-web
          file: ./dockerfiles/inim-web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/inim-web:latest
      - 
        name: Get inim-web version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/inim-web:latest
          run: echo "::set-output name=version::$(grep version /app/pkgs/inim*/inim.nimble | grep -v 'versions' | awk '{print $NF}' | tr -d '"')"
      -
        name: Build and push heywoodlh/inim-web
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/inim-web
          file: ./dockerfiles/inim-web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/inim-web:latest,heywoodlh/inim-web:${{ steps.version.outputs.version }}
