name: iperf3-buildx

on:
  schedule:
    - cron: "30 6 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download iperf3 repository
        run: |
          git clone https://github.com/heywoodlh/dockerfiles --depth=1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/iperf3
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles
          file: ./dockerfiles/iperf3/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/iperf3:latest
      - 
        name: Get iperf3 version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/iperf3:latest
          run: echo "::set-output name=version::$(dpkg -l | grep iperf3 | awk '{print $3}' | cut -d'+' -f1)"
      -
        name: Build and push heywoodlh/iperf3:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles
          file: ./dockerfiles/iperf3/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/iperf3:latest,heywoodlh/iperf3:${{ steps.version.outputs.version }}
