name: kasm-debian-buildx

on:
  schedule:
    - cron: "30 11 * * Sat"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download kasm-debian repository
        run: |
          git clone https://github.com/heywoodlh/dockerfiles --depth=1 || true
          git -C dockerfiles pull origin master --rebase
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get kasm-debian version
        id: version
        run: echo version=$(date "+%Y_%m") >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/kasm-debian:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/kasm-debian
          file: ./dockerfiles/kasm-debian/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/kasm-debian:latest,heywoodlh/kasm-debian:${{ env.version }}
