name: knockmail-buildx

on:
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download KnockMail repository
        run: |
          git clone https://github.com/heywoodlh/KnockMail knockmail
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/knockmail
        uses: docker/build-push-action@v2
        with:
          context: ./knockmail
          file: ./knockmail/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/knockmail:latest
      -
        name: Get knockmail version 
        id: version
        run: echo "::set-output name=version::$(cat knockmail/version.txt)"
      -
        name: Build and push heywoodlh/knockmail:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./knockmail
          file: ./knockmail/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/knockmail:${{ steps.version.outputs.version }}
