name: leon-buildx

on:
  schedule:
    - cron: "45 7 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download leon repository
        run: |
          git clone https://github.com/heywoodlh/dockerfiles 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/leon
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/leon
          file: ./dockerfiles/leon/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/leon:latest
      - 
        name: Get leon version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/leon:latest
          run: echo "::set-output name=version::$(cat /app/packages/leon/version.txt)"
      -
        name: Build and push heywoodlh/leon:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/leon
          file: ./dockerfiles/leon/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/leon:${{ steps.version.outputs.version }}
