name: logbash-buildx

on:
  schedule:
        - cron: "0 0 * * Mon"
  workflow_dispatch:

jobs:
  build-and-push-logbash:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/logbash
        uses: actions/checkout@master
        with:
          name: heywoodlh/logbash
          repository: heywoodlh/logbash
          path: ./logbash
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get current commit
        run: echo rev=$(git -C ./logbash rev-parse --short HEAD) >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/logbash:logbash
        uses: docker/build-push-action@v2
        with:
          context: ./logbash
          file: ./logbash/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/logbash:latest,heywoodlh/logbash:${{ env.rev }}

