name: metasploit-buildx

on:
  schedule:
        - cron: "0 0 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/metasploit
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/metasploit
          file: ./dockerfiles/metasploit/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/metasploit:latest
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m_snapshot)"
      - 
        name: Get metasploit version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/metasploit:latest
          run: echo '::set-output name=version::"'"$(msfconsole --version 2> >(awk '{print $3}' | cut -d- -f1))"'"'
      -
        name: Build and push heywoodlh/metasploit
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/metasploit
          file: ./dockerfiles/metasploit/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/metasploit:latest,heywoodlh/metasploit:${{ steps.version.outputs.version }},heywoodlh/metasploit:${{ steps.version.outputs.version }}-${{ steps.date.output.date }},heywoodlh/metasploit:${{ steps.date.output.date }}
