name: microblogpub-buildx

on:
  schedule:
        - cron: "45 6 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://git.sr.ht/~tsileo/microblog.pub
        run: git clone https://git.sr.ht/~tsileo/microblog.pub microblog.pub
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get microblogpub version
        id: version
        run: echo "::set-output name=version::$(grep "^version = " microblog.pub/pyproject.toml | awk '{print $3}' | tr -d ' "')"
      -
        name: Build and push heywoodlh/microblogpub
        uses: docker/build-push-action@v2
        with:
          context: ./microblog.pub
          file: ./microblog.pub/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/microblogpub:latest,heywoodlh/microblogpub:${{ steps.version.outputs.version }}
