on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@git.sr.ht:~heywoodlh/conf"
          source_branch: "master"
          destination_repo: "heywoodlh/conf"
          destination_branch: "master"
          source_ssh_private_key: ${{ secrets.SOURCEHUT_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.CONF_REPO_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
