name: msfbox-buildx

on:
  schedule:
        - cron: "30 0 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/msfbox
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/msfbox
          file: ./dockerfiles/msfbox/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/msfbox:latest
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m)"
      - 
        name: Get msfbox version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/msfbox:latest
          run: echo "::set-output name=version::$(cat /opt/metasploit-framework/LICENSE | grep -i 'This product includes metasploit-framework' | grep -o '[^ ]*$')"
      -
        name: Build and push heywoodlh/msfbox
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/msfbox
          file: ./dockerfiles/msfbox/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/msfbox:latest,heywoodlh/msfbox:${{ steps.version.outputs.version }},heywoodlh/msfbox:${{ steps.version.outputs.version }}-${{ steps.date.outputs.date }},heywoodlh/msfbox:${{ steps.date.outputs.date }}
