name: nfcapd-buildx

on:
  schedule:
    - cron: "15 2 * * Sat"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/nfcapd locally
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/nfcapd
          file: ./dockerfiles/nfcapd/Dockerfile
          load: true
          tags: heywoodlh/nfcapd:latest
      -
        name: Get nfcapd version
        run: |
          echo version=$(docker run --entrypoint=ash -i --rm heywoodlh/nfcapd -c "nfcapd -V | grep -oE 'Version: (.*-release.?)' | cut -d' ' -f2 | cut -d'-' -f1") >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/nfcapd:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/nfcapd
          file: ./dockerfiles/nfcapd/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/nfcapd:latest,heywoodlh/nfcapd:${{ env.version }}
