name: nfdump-buildx

on:
  schedule:
    - cron: "30 2 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles 
          repository: heywoodlh/dockerfiles 
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/nfdump
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/nfdump
          file: ./dockerfiles/nfdump/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/nfdump:latest
      - 
        name: Get nfdump version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/nfdump:latest
          run: echo "::set-output name=version::$(nfdump -V | awk '{print $(NF)}')"
      -
        name: Build and push heywoodlh/nfdump:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/nfdump
          file: ./dockerfiles/nfdump/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/nfdump:${{ steps.version.outputs.version }}
