name: nikto-buildx

on:
  schedule:
    - cron: "0 2 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/sullo/nikto
        uses: actions/checkout@master
        with:
          name: sullo/nikto 
          repository: sullo/nikto 
          path: ./nikto
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/nikto
        uses: docker/build-push-action@v2
        with:
          context: ./nikto
          file: ./nikto/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/nikto:latest
      - 
        name: Get nikto version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/nikto:latest
          run: echo "::set-output name=version::$(nikto -Version | grep 'Nikto main' | awk '{print $3}')"
      -
        name: Build and push heywoodlh/nikto:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./nikto
          file: ./nikto/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/nikto:${{ steps.version.outputs.version }}
