name: nix-buildx

on:
  schedule:
        - cron: "45 8 * * Sun"
  workflow_dispatch:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@master
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      -
        name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/nix:static locally
        uses: docker/build-push-action@master
        with:
          context: ./dockerfiles/nix
          file: ./dockerfiles/nix/Dockerfile
          load: true
          target: static-test
          tags: heywoodlh/nix-local:latest
      -
        name: Get nix static version
        run: |
          echo static_version=$(docker run -i --rm heywoodlh/nix-local nix --version | awk '{print $3}') >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/nix:static
        uses: docker/build-push-action@master
        with:
          context: ./dockerfiles/nix
          file: ./dockerfiles/nix/Dockerfile
          target: static
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/nix:static,heywoodlh/nix:static-${{ env.static_version }}
      -
        name: Build heywoodlh/nix locally
        uses: docker/build-push-action@master
        with:
          context: ./dockerfiles/nix
          file: ./dockerfiles/nix/Dockerfile
          load: true
          target: test
          tags: heywoodlh/nix-local:latest
      -
        name: Get nix version
        run: |
          echo nix_version=$(docker run -i --rm heywoodlh/nix-local nix --version | awk '{print $3}') >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/nix
        uses: docker/build-push-action@master
        with:
          context: ./dockerfiles/nix
          file: ./dockerfiles/nix/Dockerfile
          platforms: linux/amd64,linux/arm64
          target: base
          push: true
          tags: heywoodlh/nix:latest,heywoodlh/nix:${{ env.nix_version }}
      -
        name: Build heywoodlh/nix:lix locally
        uses: docker/build-push-action@master
        with:
          context: ./dockerfiles/nix
          file: ./dockerfiles/nix/Dockerfile
          load: true
          target: lix-test
          tags: heywoodlh/lix-local:latest
      -
        name: Get lix version
        run: |
          echo lix_version=$(docker run -i --rm heywoodlh/lix-local nix --version | awk '{print $3}') >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/nix
        uses: docker/build-push-action@master
        with:
          context: ./dockerfiles/nix
          file: ./dockerfiles/nix/Dockerfile
          platforms: linux/amd64,linux/arm64
          target: lix
          push: true
          tags: heywoodlh/nix:lix,heywoodlh/nix:lix-${{ env.lix_version }}
