name: nuclei-buildx

on:
  schedule:
        - cron: "30 3 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/projectdiscovery/nuclei
        uses: actions/checkout@master
        with:
          name: projectdiscovery/nuclei
          repository: projectdiscovery/nuclei
          path: ./nuclei
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/nuclei
        uses: docker/build-push-action@v2
        with:
          context: ./nuclei
          file: ./nuclei/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/nuclei:latest
      - 
        name: Get nuclei version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/nuclei:latest
          run: echo "::set-output name=version::$(nuclei --version &> /tmp/version.txt && tail -1 /tmp/version.txt | cut -d': ' -f 2 | tr -d ' ')"
      -
        name: Build and push heywoodlh/nuclei:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./nuclei
          file: ./nuclei/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/nuclei:${{ steps.version.outputs.version }}
