name: nuclei-buildx

on:
  schedule:
        - cron: "0 9 * * Sun"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/projectdiscovery/nuclei
        uses: actions/checkout@master
        with:
          name: projectdiscovery/nuclei
          repository: projectdiscovery/nuclei
          path: ./nuclei
          ref: "dev"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/nuclei locally
        uses: docker/build-push-action@v2
        with:
          context: ./nuclei
          file: ./nuclei/Dockerfile
          load: true
          tags: heywoodlh/nuclei-local:latest
      -
        name: Get nuclei version
        run: |
          echo version="$({ docker run -i --rm heywoodlh/nuclei-local -version; } &> >(head -1) | cut -d':' -f2 | tr -d ' ')" >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/nuclei
        uses: docker/build-push-action@v2
        with:
          context: ./nuclei
          file: ./nuclei/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/nuclei:latest,heywoodlh/nuclei:${{ env.version }}
