name: ollama-lb-buildx

on:
  schedule:
    - cron: "0 2 * * Mon"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/ollama_load_balancer
          repository: heywoodlh/ollama_load_balancer
          path: ./ollama_load_balancer
          ref: nix-docker-support
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/ollama_load_balancer locally
        uses: docker/build-push-action@v2
        with:
          context: ./ollama_load_balancer
          file: ./ollama_load_balancer/Dockerfile
          load: true
          tags: heywoodlh/ollama_load_balancer:latest
      -
        name: Get version
        run: |
          echo version=$(docker run -i --rm heywoodlh/ollama_load_balancer:latest --version | awk '{print $2}') >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/ollama_load_balancer:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./ollama_load_balancer
          file: ./ollama_load_balancer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/ollama_load_balancer:latest,heywoodlh/ollama_load_balancer:${{ env.version }}
