name: openrc-buildx

on:
  schedule:
    - cron: "15 15 * * Sat"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test images
        run: |
          ./dockerfiles/openrc/openrc-test.sh
      -
        name: Get current month
        run: echo date=$(date +%Y_%m) >> $GITHUB_ENV
      -
        name: Build heywoodlh/openrc locally
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/openrc
          file: ./dockerfiles/openrc/Dockerfile
          load: true
          tags: heywoodlh/openrc-test:latest
      - name: Run test
        run: echo alpine_version=$(docker run --entrypoint=ash -i --rm heywoodlh/openrc-test -c "cat /etc/os-release | grep VERSION_ID | cut -d'=' -f2") >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/openrc
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/openrc
          file: ./dockerfiles/openrc/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/openrc:latest,heywoodlh/openrc:${{ env.alpine_version }},heywoodlh/openrc:${{ env.alpine_version }}-${{ env.date }},heywoodlh/openrc:${{ env.date }}
