name: powershell-buildx

on:
  schedule:
        - cron: "0 6 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/powershell
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/powershell
          file: ./dockerfiles/powershell/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/powershell:latest
      - 
        name: Get current version
        run: |
          echo version="$(docker run -it --rm heywoodlh/powershell:latest -Version | awk '{print $2}')" >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/powershell
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/powershell
          file: ./dockerfiles/powershell/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/powershell:latest,heywoodlh/powershell:${{ env.version }}
