name: rdp-kali-linux-full-buildx

on:
  schedule:
        - cron: "30 6 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/rdp-kali-linux-full
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/rdp-kali-linux-full
          file: ./dockerfiles/rdp-kali-linux-full/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/rdp-kali-linux-full:latest
      - 
        name: Get rdp-kali-linux-full version
        run: |
          echo version=$(docker run -i --rm --entrypoint bash heywoodlh/rdp-kali-linux-full:latest -c 'cat /etc/os-release | grep VERSION= | cut -d\" -f2') >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/rdp-kali-linux-full
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/rdp-kali-linux-full
          file: ./dockerfiles/rdp-kali-linux-full/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/rdp-kali-linux-full:latest,heywoodlh/rdp-kali-linux-full:${{ env.version }}
