name: rdp-kali-linux-buildx

on:
  schedule:
        - cron: "30 3 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/rdp-kali-linux
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/rdp-kali-linux
          file: ./dockerfiles/rdp-kali-linux/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/rdp-kali-linux:latest
      - 
        name: Get rdp-kali-linux version
        id: version
        run: echo "::set-output name=version::$(cat dockerfiles/rdp-kali-linux/VERSION)"
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m_snapshot)"
      -
        name: Build and push heywoodlh/rdp-kali-linux
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/rdp-kali-linux
          file: ./dockerfiles/rdp-kali-linux/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/rdp-kali-linux:latest,heywoodlh/rdp-kali-linux:${{ steps.version.outputs.version }},heywoodlh/rdp-kali-linux:${{ steps.version.outputs.version}}-${{ steps.date.outputs.date }}
