name: reverse-shell-buildx

on:
  schedule:
    - cron: "15 15 * * Sat"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/reverse-shell locally
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/reverse-shell
          file: ./dockerfiles/reverse-shell/Dockerfile
          target: base
          load: true
          tags: heywoodlh/reverse-shell-test:latest
      -
        name: Get alpine version
        run: |
          echo alpine_version=$(docker run --entrypoint=ash -i --rm heywoodlh/reverse-shell-test -c "cat /etc/os-release | grep VERSION_ID | cut -d'=' -f2") >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/reverse-shell:server
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/reverse-shell
          file: ./dockerfiles/reverse-shell/Dockerfile
          target: server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/reverse-shell:server,heywoodlh/reverse-shell:server-alpine,heywoodlh/reverse-shell:server-alpine-${{ env.alpine_version }}

      -
        name: Build and push heywoodlh/reverse-shell:client
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/reverse-shell
          file: ./dockerfiles/reverse-shell/Dockerfile
          target: client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/reverse-shell:client,heywoodlh/reverse-shell:client-alpine,heywoodlh/reverse-shell:client-alpine-${{ env.alpine_version }}
