name: rustdesk-web-buildx

on:
  schedule:
        - cron: "0 0 * * Sat"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/rustdesk-web locally
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/rustdesk-web
          file: ./dockerfiles/rustdesk-web/Dockerfile
          load: true
          tags: heywoodlh/rustdesk-test:latest
      -
        name: Get rustdesk-web version
        run: |
          echo version=$(docker run -i --rm --entrypoint=bash heywoodlh/rustdesk-test -c "dpkg -l | grep rustdesk | awk '{print \$3}'") >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/rustdesk-web
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/rustdesk-web
          file: ./dockerfiles/rustdesk-web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/rustdesk-web:latest,heywoodlh/rustdesk-web:${{ env.version }}
