name: shodan-cli-buildx

on:
  schedule:
    - cron: "15 0 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/shodan-cli
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/shodan-cli
          file: ./dockerfiles/shodan-cli/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/shodan-cli:latest
      - 
        name: Get shodan-cli version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/shodan-cli:latest
          run: echo "::set-output name=version::$(shodan version)"
      -
        name: Build and push heywoodlh/shodan-cli:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/shodan-cli
          file: ./dockerfiles/shodan-cli/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/shodan-cli:latest,heywoodlh/shodan-cli:${{ steps.version.outputs.version }}
