name: spodcast-web-buildx

on:
  schedule:
  - cron: "7 20 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/Spodcast
        uses: actions/checkout@master
        with:
          name: heywoodlh/Spodcast
          repository: heywoodlh/Spodcast
          path: ./Spodcast
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m_snapshot)"
      -
        name: Build and push heywoodlh/spodcast-web
        uses: docker/build-push-action@v2
        with:
          context: ./Spodcast
          file: ./Spodcast/docker/Dockerfile.web
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/spodcast-web:latest,heywoodlh/spodcast-web:${{ steps.date.outputs.date }}
