name: spodcast-cron-buildx

on:
  schedule:
    - cron: "15 4 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download spodcast repository
        run: |
          git clone https://github.com/heywoodlh/Spodcast spodcast
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/spodcast
        uses: docker/build-push-action@v2
        with:
          context: ./spodcast
          file: ./spodcast/docker/Dockerfile.cron
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/spodcast-cron:latest
      -
        name: Get spodcast version 
        id: version
        run: echo "::set-output name=version::$(grep version spodcast/setup.cfg | awk '{print $3}')"
      -
        name: Build and push heywoodlh/spodcast:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./spodcast
          file: ./spodcast/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/spodcast-cron:${{ steps.version.outputs.version }}
