name: ssh-git-buildx

on:
  schedule:
    - cron: "10 2 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/ssh-git
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/ssh-git
          file: ./dockerfiles/ssh-git/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/ssh-git:latest
      - 
        name: Get ssh-git version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/ssh-git:latest
          run: echo "::set-output name=version::$(dpkg -l | grep openssh-server | awk '{print $3}' | cut -d':' -f2 | cut -d'p' -f1)"
      -
        name: Build and push heywoodlh/ssh-git:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/ssh-git
          file: ./dockerfiles/ssh-git/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/ssh-git:${{ steps.version.outputs.version }}
