name: ssh-chat-buildx

on:
  schedule:
        - cron: "0 11 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/shazow/ssh-chat
        uses: actions/checkout@master
        with:
          name: shazow/ssh-chat 
          repository: shazow/ssh-chat 
          path: ./ssh-chat
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get ssh-chat version
        run: |
          echo version=$(git -C ./ssh-chat describe --tags --dirty --always | cut -d '-' -f1) >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/ssh-chat
        uses: docker/build-push-action@v2
        with:
          context: ./ssh-chat/
          file: ./ssh-chat/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/ssh-chat:latest,heywoodlh/ssh-chat:${{ env.version }}
