name: sso-buildx

on:
  schedule:
    - cron: "30 4 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/buzzfeed/sso
        uses: actions/checkout@master
        with:
          name: buzzfeed/sso
          repository: buzzfeed/sso
          path: ./sso
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get sso version
        id: version
        run: echo "::set-output name=version::$(grep version sso/Makefile | grep ':=' | awk '{print $3}' | tr -d \")"
      -
        name: Build and push heywoodlh/sso:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./sso
          file: ./sso/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/sso:latest,heywoodlh/sso:${{ steps.version.outputs.version }}
