name: sublist3r-buildx

on:
  schedule:
        - cron: "30 2 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/sublist3r
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/sublist3r
          file: ./dockerfiles/sublist3r/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/sublist3r:latest
      - 
        name: Get sublist3r version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/sublist3r:latest
          run: echo "::set-output name=version::$(dpkg -l | grep sublist3r | awk '{print $3}' | cut -d'-' -f1)"
      -
        name: Build and push heywoodlh/sublist3r
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/sublist3r
          file: ./dockerfiles/sublist3r/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/sublist3r:latest,heywoodlh/sublist3r:${{ steps.version.outputs.version }}
