name: sunshine-buildx

on:
  schedule:
        - cron: "0 13 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/sunshine locally
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/sunshine
          file: ./dockerfiles/sunshine/Dockerfile
          load: true
          tags: heywoodlh/sunshine-test:latest
      - name: Run test
        run: docker run -i --rm heywoodlh/sunshine-test
      - 
        name: Get current month
        run: echo date=$(date +%Y_%m) >> $GITHUB_ENV
      -
        name: Get sunshine version
        run: |
          echo version=$(docker run -i --rm --entrypoint=bash heywoodlh/sunshine-test -c "pacman -Q | grep sunshine | awk '{print $2}'") >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/sunshine
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/sunshine
          file: ./dockerfiles/sunshine/Dockerfile
          platforms: linux/amd64
          push: true
          tags: heywoodlh/sunshine:latest,heywoodlh/sunshine:${{ env.version }}
