name: sync home-manager repo

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync home-manager master
        run: gh repo sync heywoodlh/home-manager -b master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
