name: tabby-web-buildx

on:
  schedule:
    - cron: "30 0 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone https://github.com/Eugeny/tabby-web
        uses: actions/checkout@master
        with:
          name: Eugeny/tabby-web
          repository: Eugeny/tabby-web
          path: ./tabby-web
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/tabby-web
        uses: docker/build-push-action@v2
        with:
          context: ./tabby-web
          file: ./tabby-web/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/tabby-web:latest
