name: tailscale-dns-bridge-buildx

on:
  schedule:
    - cron: "15 15 * * Sat"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build heywoodlh/tailscale-dns-bridge locally
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/tailscale-dns-bridge
          file: ./dockerfiles/tailscale-dns-bridge/Dockerfile
          load: true
          tags: heywoodlh/tailscale-dns-bridge-test:latest
      -
        name: Get tailscale version
        run: |
          echo version=$(docker run --entrypoint=ash -i --rm heywoodlh/tailscale-dns-bridge-test -c "tailscale --version | head -1") >> $GITHUB_ENV
      -
        name: Build and push heywoodlh/tailscale-dns-bridge
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/tailscale-dns-bridge
          file: ./dockerfiles/tailscale-dns-bridge/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/tailscale-dns-bridge:latest,heywoodlh/tailscale-dns-bridge:${{ env.version }}
