name: takeover-buildx

on:
  schedule:
        - cron: "30 4 * * Sat"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/takeover
        uses: actions/checkout@master
        with:
          name: heywoodlh/takeover 
          repository: heywoodlh/takeover
          path: ./takeover
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/takeover
        uses: docker/build-push-action@v2
        with:
          context: ./takeover
          file: ./takeover/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/takeover:latest
      - 
        name: Get takeover version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/takeover:latest
          run: echo "::set-output name=version::$(grep version /app/setup.py | cut -d"'" -f 2)"
      -
        name: Build and push heywoodlh/takeover
        uses: docker/build-push-action@v2
        with:
          context: ./takeover
          file: ./takeover/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/takeover:latest,heywoodlh/takeover:${{ steps.version.outputs.version }}
