name: tor-socks-proxy-buildx

on:
  schedule:
    - cron: "30 0 * * Mon"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/PeterDaveHello/tor-socks-proxy
        uses: actions/checkout@master
        with:
          name: PeterDaveHello/tor-socks-proxy
          repository: PeterDaveHello/tor-socks-proxy
          path: ./tor-socks-proxy

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build tor-socks-proxy locally
        uses: docker/build-push-action@v2
        with:
          context: ./tor-socks-proxy
          file: ./tor-socks-proxy/Dockerfile
          load: true
          tags: docker.io/heywoodlh/tor-socks-proxy-local:latest

      -
        name: Get tor-socks-proxy version
        id: version
        run: echo version=$(docker run -i --rm --entrypoint=ash docker.io/heywoodlh/tor-socks-proxy-local -c "tor --version" | head -1 | awk '{print $3}' | sed 's/\.$//g') >> $GITHUB_ENV

      -
        name: Build and push heywoodlh/tor-socks-proxy:${{ steps.version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./tor-socks-proxy
          file: ./tor-socks-proxy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/tor-socks-proxy:latest,heywoodlh/tor-socks-proxy:${{ env.version }}
