name: trizen-buildx

on:
  schedule:
        - cron: "15 0 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/trizen
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/trizen
          file: ./dockerfiles/trizen/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/trizen:latest
      - 
        name: Get trizen version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/trizen:latest
          run: echo "::set-output name=version::$(pacman -Q | grep trizen | cut -d':' -f2')"
      -
        name: Build and push heywoodlh/trizen
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/trizen
          file: ./dockerfiles/trizen/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/trizen:latest,heywoodlh/trizen:${{ steps.version.outputs.version }}
