name: warpgate-buildx

on:
  schedule:
        - cron: "15 0 * * *"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/warp-tech/warpgate
        uses: actions/checkout@master
        with:
          name: warp-tech/warpgate 
          repository: warp-tech/warpgate
          path: ./warpgate
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push heywoodlh/warpgate
        uses: docker/build-push-action@v2
        with:
          context: ./warpgate
          file: ./warpgate/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: heywoodlh/warpgate:latest
      - 
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - 
        name: Get warpgate version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: heywoodlh/warpgate:latest
          run: echo "::set-output name=version::$(warpgate --version | tail -1 | awk '{print $2}')"
      -
        name: Build and push heywoodlh/warpgate
        uses: docker/build-push-action@v2
        with:
          context: ./warpgate
          file: ./warpgate/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: heywoodlh/warpgate:latest,heywoodlh/warpgate:${{ steps.version.outputs.version }}
