name: x13s-nixos

on:
  schedule:
    - cron: "30 0 * * 0"
  workflow_dispatch:

jobs:
  kernel:
    runs-on: [self-hosted, linux, arm64]

    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: set home
        run: |
          echo "HOME=$PWD" >> "$GITHUB_ENV"

      - name: build all
        run: |
          cd
          set -x
          git clone https://codeberg.org/adamcstephens/nixos-x13s || true
          cd nixos-x13s && git pull origin main
          nix develop .#ci -c just -- find-targets
          nix develop .#ci -c just -- build

      - name: upload to cachix
        run: |
          cd
          nix run --impure nixpkgs#cachix -- push heywoodlh-nixos-x13s $(cat nixos-x13s/outputs)
        env:
          CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_TOKEN_X13S }}'
