name: x13s-nixos

on:
  schedule:
    - cron: "30 0 * * 0"
  workflow_dispatch:

jobs:
  kernel:
    name: Build x13s kernel (ARM64)
    runs-on: [ubuntu-24.04-arm]
    steps:
      - name: Login to Tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            extra-substituters = http://attic/nixos
            extra-trusted-public-keys = nixos:uRCswSsap/ho6e2Vp4HXpH9SMdN4rW62N8Uq3r+mQ5E=

      - name: build kernel
        shell: bash
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          cd
          set -x
          mkdir -p ~/.config/attic
          printf "default-server = \"kube\"\n\n[servers.kube]\nendpoint = \"http://attic\"\ntoken = \"$ATTIC_TOKEN\"" > ~/.config/attic/config.toml
          nix build "github:BrainWart/x13s-nixos#packages.aarch64-linux.x13s.linux_jhovold"
          nix run "github:zhaofengli/attic/47752427561f1c34debb16728a210d378f0ece36#attic-client" -- push nixos ./result
