name: x13s-nixos

on:
  schedule:
    - cron: "30 0 * * 0"
  workflow_dispatch:

jobs:
  kernel:
    runs-on: [self-hosted, linux, arm64]

    steps:
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: set home
        run: |
          echo "HOME=$PWD" >> "$GITHUB_ENV"

      - name: build all
        run: |
          set -x
          git clone https://codeberg.org/adamcstephens/nixos-x13s || true
          cd nixos-x13s && git pull origin main
          TARGETS=$(nix eval .#packages.aarch64-linux --apply 'builtins.attrNames' --json | jq '. | map(".#" + .) | join(" ")' -r)
          OUTPUT=$(nix build --print-out-paths --keep-going $TARGETS)
          echo $OUTPUT
          echo "$OUTPUT" > build.out

      - name: upload to cachix
        run: |
          nix run --impure nixpkgs#cachix -- push heywoodlh-nixos-x13s $(cat build.out)
        env:
          CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_TOKEN_X13S }}'
